import { Theme } from '../theme.types';

export const cyberpunk: Theme = {
  name: 'Cyberpunk',
  slug: 'cyberpunk',
  background: {
    page: '#0d0d0d',
    card: '#1a1a1a',
    cardHover: '#222222',
    code: '#0a0a0a',
  },
  text: {
    primary: '#f5f500',
    secondary: '#b0b000',
    heading: '#00ff41',
    link: '#00ff41',
    linkHover: '#f5f500',
    inverse: '#0d0d0d',
  },
  accent: {
    primary: '#00ff41',
    secondary: '#ff003c',
    highlight: '#f5f500',
    danger: '#ff003c',
    success: '#00ff41',
    decorative: '#00ff41',
  },
  border: {
    default: 'rgba(0, 255, 65, 0.2)',
    focus: '#f5f500',
    decorative: '#00ff41',
    radius: '0',
  },
  ui: {
    navBg: '#0a0a0a',
    navText: '#f5f500',
    navLinkActive: '#00ff41',
    navLinkInactive: '#f5f500',
    navLinkHoverBorder: '#00ff41',
    footerBg: '#0a0a0a',
    footerText: '#f5f500',
    footerLink: '#00ff41',
    footerLinkHidden: '#0a0a0a',
  },
  palette: {
    yellow: '#f5f500',
    orange: '#ff8c00',
    red: '#ff003c',
    magenta: '#ff00ff',
    violet: '#9d00ff',
    blue: '#00b4d8',
    cyan: '#00ffff',
    green: '#00ff41',
  },
  meta: {
    fontFamily: "'Fira Code'",
    borderStyle: 'solid',
    cardBorderStyle: '0.1rem solid rgba(0, 255, 65, 0.3)',
    cardBoxShadow: '0 0 1rem rgba(0, 255, 65, 0.1)',
    codeTheme: 'a11yDark',
    decoratorColor: '#00ff41',
    backgroundCss: [
      'background-image: repeating-linear-gradient(',
      '  to bottom,',
      '  transparent,',
      '  transparent 2px,',
      '  rgba(0, 255, 65, 0.04) 2px,',
      '  rgba(0, 255, 65, 0.04) 4px',
      ');',
    ].join('\n'),
    headingTransform: 'uppercase',
    headingLetterSpacing: '0.15em',
    headingCss: 'font-weight: 700; text-shadow: 0.2rem 0 #ff003c, -0.2rem 0 #00fff5;',
    navCss: [
      'border-bottom: 0.1rem solid #00ff41;',
      'box-shadow: 0 0.1rem 0.5rem rgba(0, 255, 65, 0.2);',
      'font-variant-ligatures: none;',
    ].join('\n'),
    navLinkCss: [
      '&::before {',
      "  content: '> ';",
      '  color: #00ff41;',
      "  font-family: 'Fira Code';",
      '  text-shadow: 0 0 0.3rem #00ff41;',
      '}',
      'transition: all 0.05s linear;',
      '&:hover {',
      '  text-shadow: 0 0 0.5rem currentColor;',
      '  background-color: rgba(0, 255, 65, 0.05);',
      '}',
    ].join('\n'),
    cardCss: [
      'clip-path: polygon(1.2rem 0, 100% 0, 100% calc(100% - 1.2rem), calc(100% - 1.2rem) 100%, 0 100%, 0 1.2rem);',
      'border: none;',
      'transition: all 0.05s linear;',
    ].join('\n'),
    cardHoverCss: [
      'transform: translate(0.2rem, -0.1rem);',
      'filter: drop-shadow(-0.2rem 0 #ff003c) drop-shadow(0.2rem 0 #00fff5);',
    ].join('\n'),
    decoratorCss: [
      'background-color: transparent;',
      'height: auto;',
      'width: auto;',
      '&::before {',
      "  content: '\\25AE';",
      '  color: #00ff41;',
      '  font-size: 2rem;',
      '  animation: blink-cursor 1s step-end infinite;',
      '}',
    ].join('\n'),
    footerCss: [
      'border-top: 0.1rem solid rgba(0, 255, 65, 0.3);',
      'font-variant-ligatures: none;',
      '&::before {',
      "  content: 'SYS.OK';",
      '  color: #00ff41;',
      '  font-size: 1.2rem;',
      "  font-family: 'Fira Code';",
      '  opacity: 0.5;',
      '  margin-right: 1.2rem;',
      '}',
    ].join('\n'),
    globalCss: [
      'body {',
      '  cursor: crosshair;',
      '}',
      'a, button {',
      '  cursor: crosshair;',
      '}',
      '::selection {',
      '  background-color: #00ff41;',
      '  color: #0d0d0d;',
      '}',
      '@keyframes blink-cursor {',
      '  0%, 100% { opacity: 1; }',
      '  50% { opacity: 0; }',
      '}',
      '@keyframes glitch-shift {',
      '  0%, 100% { transform: translate(0); }',
      '  20% { transform: translate(-0.2rem, 0.1rem); }',
      '  40% { transform: translate(0.2rem, -0.1rem); }',
      '  60% { transform: translate(-0.1rem, -0.1rem); }',
      '  80% { transform: translate(0.1rem, 0.1rem); }',
      '}',
      'body::after {',
      "  content: '';",
      '  position: fixed;',
      '  top: 0;',
      '  left: 0;',
      '  width: 100%;',
      '  height: 100%;',
      '  pointer-events: none;',
      '  z-index: 9999;',
      '  background: repeating-linear-gradient(',
      '    to bottom,',
      '    transparent,',
      '    transparent 2px,',
      '    rgba(0, 255, 65, 0.03) 2px,',
      '    rgba(0, 255, 65, 0.03) 4px',
      '  );',
      '}',
    ].join('\n'),
  },
};
