import { Theme } from '../theme.types';

export const futurism: Theme = {
  name: 'Futurism',
  slug: 'futurism',
  background: {
    page: '#ffffff',
    card: '#f0f0f0',
    cardHover: '#e8e8e8',
    code: '#1a1a1a',
  },
  text: {
    primary: '#000000',
    secondary: '#333333',
    heading: '#000000',
    link: '#ff3300',
    linkHover: '#cc2900',
    inverse: '#ffffff',
  },
  accent: {
    primary: '#ff3300',
    secondary: '#cccccc',
    highlight: '#ff6600',
    danger: '#cc0000',
    success: '#006600',
    decorative: '#ff3300',
  },
  border: {
    default: '#000000',
    focus: '#ff3300',
    decorative: '#ff3300',
    radius: '0',
  },
  ui: {
    navBg: '#000000',
    navText: '#ffffff',
    navLinkActive: '#ff3300',
    navLinkInactive: '#ffffff',
    navLinkHoverBorder: '#ff3300',
    footerBg: '#000000',
    footerText: '#ffffff',
    footerLink: '#ff3300',
    footerLinkHidden: '#000000',
  },
  palette: {
    yellow: '#ffcc00',
    orange: '#ff6600',
    red: '#ff3300',
    magenta: '#cc0066',
    violet: '#6600cc',
    blue: '#0033cc',
    cyan: '#009999',
    green: '#339900',
  },
  meta: {
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    fontFamilyHeading: "'Impact', 'Haettenschweiler', 'Arial Narrow Bold', sans-serif",
    borderStyle: 'solid',
    cardBorderStyle: '0.1rem solid #000000',
    cardBoxShadow: 'none',
    codeTheme: 'a11yDark',
    decoratorColor: '#ff3300',
    backgroundCss: [
      'background-image: repeating-linear-gradient(',
      '  -45deg,',
      '  transparent,',
      '  transparent 20px,',
      '  rgba(0, 0, 0, 0.03) 20px,',
      '  rgba(0, 0, 0, 0.03) 21px,',
      '  transparent 21px,',
      '  transparent 40px,',
      '  rgba(255, 51, 0, 0.03) 40px,',
      '  rgba(255, 51, 0, 0.03) 41px',
      ');',
    ].join('\n'),
    headingTransform: 'uppercase',
    headingLetterSpacing: '0.1em',
    headingFontStyle: 'italic',
    headingCss: [
      'font-weight: 900;',
      'font-style: italic;',
      'transform: skewX(calc(-2deg + var(--scroll-velocity, 0) * -8deg));',
      'text-shadow: calc(var(--scroll-velocity, 0) * 0.5rem) 0 0.1rem rgba(255, 51, 0, 0.3);',
      'transition: transform 300ms ease-out, text-shadow 300ms ease-out;',
    ].join('\n'),
    bodyCss: [
      'transform: skewX(calc(var(--scroll-velocity, 0) * -3deg));',
      'transition: transform 300ms ease-out;',
    ].join('\n'),
    navCss: ['transform: skewX(-3deg);', 'border-bottom: 0.3rem solid #ff3300;'].join('\n'),
    navLinkCss: [
      'display: inline-block;',
      'transform: skewX(3deg);',
      'padding: 0.4rem 0.8rem;',
      'transition: all 0.1s linear;',
      '&:hover {',
      '  background-color: #ff3300;',
      '  color: #ffffff;',
      '  border-color: #ff3300;',
      '}',
    ].join('\n'),
    cardCss: [
      'transform: skewX(-1deg);',
      'border-left: 0.6rem solid #ff3300;',
      'transition: all 0.1s linear;',
    ].join('\n'),
    cardHoverCss: [
      'transform: skewX(-1deg) translateX(0.8rem);',
      'box-shadow: -0.4rem 0 0 #ff3300;',
    ].join('\n'),
    decoratorCss: [
      'background-color: transparent;',
      'height: auto;',
      'width: auto;',
      '&::before {',
      "  content: '///';",
      '  color: #ff3300;',
      '  font-size: 2rem;',
      '  font-weight: 900;',
      '  font-style: italic;',
      '  letter-spacing: -0.1em;',
      '}',
    ].join('\n'),
    footerCss: [
      'clip-path: polygon(0 30%, 100% 0, 100% 100%, 0 100%);',
      'padding-top: 3.2rem;',
    ].join('\n'),
    globalCss: '',
  },
};
