import { Theme } from '../theme.types';

export const geocities: Theme = {
  name: 'GeoCities',
  slug: 'geocities',
  background: {
    page: '#000000',
    card: '#000080',
    cardHover: '#0000a0',
    code: '#000000',
  },
  text: {
    primary: '#00ff00',
    secondary: '#ffff00',
    heading: '#ff00ff',
    link: '#00ffff',
    linkHover: '#ff00ff',
    inverse: '#000000',
  },
  accent: {
    primary: '#ffff00',
    secondary: '#ff00ff',
    highlight: '#00ffff',
    danger: '#ff0000',
    success: '#00ff00',
    decorative: '#ff00ff',
  },
  border: {
    default: '#ffff00',
    focus: '#00ffff',
    decorative: '#ff00ff',
    radius: '0',
  },
  ui: {
    navBg: '#ff6600',
    navText: '#ffffff',
    navLinkActive: '#ffff00',
    navLinkInactive: '#ffffff',
    navLinkHoverBorder: '#ffff00',
    footerBg: '#ff6600',
    footerText: '#ffffff',
    footerLink: '#ffff00',
    footerLinkHidden: '#ff6600',
  },
  palette: {
    yellow: '#ffff00',
    orange: '#ff6600',
    red: '#ff0000',
    magenta: '#ff00ff',
    violet: '#9900ff',
    blue: '#0000ff',
    cyan: '#00ffff',
    green: '#00ff00',
  },
  meta: {
    fontFamily: "'Comic Sans MS', 'Comic Sans', cursive",
    fontFamilyHeading: "'Times New Roman', 'Georgia', serif",
    codeTheme: 'a11yDark',
    decoratorColor: '#ff00ff',
  },
};
