import { Theme } from '../theme.types';

export const geocities: Theme = {
  name: 'GeoCities',
  slug: 'geocities',
  background: {
    page: '#000000',
    card: '#000080',
    cardHover: '#0000a0',
    code: '#000000',
  },
  text: {
    primary: '#00ff00',
    secondary: '#ffff00',
    heading: '#ff00ff',
    link: '#00ffff',
    linkHover: '#ff00ff',
    inverse: '#000000',
  },
  accent: {
    primary: '#ffff00',
    secondary: '#ff00ff',
    highlight: '#00ffff',
    danger: '#ff0000',
    success: '#00ff00',
    decorative: '#ff00ff',
  },
  border: {
    default: '#ffff00',
    focus: '#00ffff',
    decorative: '#ff00ff',
    radius: '0',
  },
  ui: {
    navBg: '#ff6600',
    navText: '#ffffff',
    navLinkActive: '#ffff00',
    navLinkInactive: '#ffffff',
    navLinkHoverBorder: '#ffff00',
    footerBg: '#ff6600',
    footerText: '#ffffff',
    footerLink: '#ffff00',
    footerLinkHidden: '#ff6600',
  },
  palette: {
    yellow: '#ffff00',
    orange: '#ff6600',
    red: '#ff0000',
    magenta: '#ff00ff',
    violet: '#9900ff',
    blue: '#0000ff',
    cyan: '#00ffff',
    green: '#00ff00',
  },
  meta: {
    fontFamily: "'Comic Sans MS', 'Comic Sans', cursive",
    fontFamilyHeading: "'Times New Roman', 'Georgia', serif",
    borderStyle: 'dashed',
    cardBorderStyle: '0.3rem dashed #ffff00',
    cardBoxShadow: 'none',
    codeTheme: 'a11yDark',
    decoratorColor: '#ff00ff',
    backgroundCss: [
      'background-image:',
      '  radial-gradient(1px 1px at 20px 30px, #ffffff, rgba(0,0,0,0)),',
      '  radial-gradient(1px 1px at 40px 70px, #ffffff, rgba(0,0,0,0)),',
      '  radial-gradient(2px 2px at 90px 40px, #ffff00, rgba(0,0,0,0)),',
      '  radial-gradient(2px 2px at 160px 120px, #00ffff, rgba(0,0,0,0)),',
      '  radial-gradient(1px 1px at 240px 90px, #ff00ff, rgba(0,0,0,0));',
      'background-size: 300px 300px;',
    ].join('\n'),
    headingCss: ['text-align: center;', 'text-shadow: 0.2rem 0.2rem #ff00ff;'].join('\n'),
    navCss: [
      'justify-content: center;',
      'flex-wrap: wrap;',
      'border-bottom: 0.3rem double #ffff00;',
      'border-top: 0.3rem double #ffff00;',
      'height: auto;',
      'padding: 1.2rem;',
      'background: #000080;',
      'background-image: repeating-linear-gradient(90deg, transparent, transparent 4px, rgba(255,255,255,0.03) 4px, rgba(255,255,255,0.03) 8px);',
    ].join('\n'),
    navLinkCss: [
      'text-decoration: underline;',
      'border: none;',
      'border-bottom: none;',
      'font-weight: bold;',
      'font-size: 1.8em;',
      '&:hover {',
      '  color: #ff0000;',
      '  border: none;',
      '  border-bottom: none;',
      '  animation: rainbow-shift 2s linear infinite;',
      '}',
    ].join('\n'),
    cardCss: [
      'border: 0.4rem ridge #ff00ff;',
      'border-radius: 0;',
      'box-shadow: none;',
      'background-image: repeating-linear-gradient(',
      '  45deg,',
      '  transparent,',
      '  transparent 10px,',
      '  rgba(0, 0, 255, 0.05) 10px,',
      '  rgba(0, 0, 255, 0.05) 20px',
      ');',
      'transition: none;',
    ].join('\n'),
    cardHoverCss: [
      'transform: none;',
      'border-color: #00ffff;',
      'box-shadow: 0 0 0 0.3rem #ff00ff;',
      'background-color: #000040;',
    ].join('\n'),
    decoratorCss: [
      'height: 0.6rem;',
      'width: 100%;',
      'background: linear-gradient(to right, #ff0000, #ff8800, #ffff00, #00ff00, #0000ff, #8800ff, #ff0088);',
      'border-radius: 0;',
    ].join('\n'),
    footerCss: [
      'flex-direction: column;',
      'height: auto;',
      'padding: 1.6rem;',
      'gap: 0.8rem;',
      'border-top: 0.3rem double #ffff00;',
      '&::before {',
      "  content: 'Best viewed in Netscape Navigator 4.0 at 800x600';",
      '  font-size: 1rem;',
      '  color: #00ffff;',
      "  font-family: 'Times New Roman', serif;",
      '  text-align: center;',
      '  display: block;',
      '  order: 1;',
      '}',
      '&::after {',
      "  content: 'You are visitor #004,721';",
      '  font-size: 1.2rem;',
      '  color: #ffff00;',
      "  font-family: 'Comic Sans MS', cursive;",
      '  text-align: center;',
      '  display: block;',
      '  order: 2;',
      '}',
    ].join('\n'),
    globalCss: [
      '@keyframes blink-text {',
      '  0%, 100% { opacity: 1; }',
      '  50% { opacity: 0; }',
      '}',
      '@keyframes marquee-scroll {',
      '  0% { transform: translateX(100%); }',
      '  100% { transform: translateX(-100%); }',
      '}',
      '@keyframes rainbow-shift {',
      '  0% { color: #ff0000; }',
      '  16% { color: #ff8800; }',
      '  33% { color: #ffff00; }',
      '  50% { color: #00ff00; }',
      '  66% { color: #0000ff; }',
      '  83% { color: #ff00ff; }',
      '  100% { color: #ff0000; }',
      '}',
      "body { cursor: url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'%3E%3Ctext y='20' font-size='20'%3E%E2%9C%A8%3C/text%3E%3C/svg%3E\") 12 12, auto; }",
      '::selection {',
      '  background-color: #ff00ff;',
      '  color: #ffff00;',
      '}',
    ].join('\n'),
  },
};
