import { Theme } from '../theme.types';

export const windows98: Theme = {
  name: 'Windows 98',
  slug: 'windows-98',
  background: {
    page: '#008080',
    card: '#c0c0c0',
    cardHover: '#d4d4d4',
    code: '#ffffff',
  },
  text: {
    primary: '#000000',
    secondary: '#404040',
    heading: '#000000',
    link: '#0000ff',
    linkHover: '#0000cc',
    inverse: '#ffffff',
  },
  accent: {
    primary: '#000080',
    secondary: '#ffffff',
    highlight: '#000080',
    danger: '#ff0000',
    success: '#008000',
    decorative: '#000080',
  },
  border: {
    default: '#808080',
    focus: '#000000',
    decorative: '#000080',
    radius: '0',
  },
  ui: {
    navBg: '#000080',
    navText: '#000000',
    navLinkActive: '#000000',
    navLinkInactive: '#000000',
    navLinkHoverBorder: '#000000',
    footerBg: '#c0c0c0',
    footerText: '#000000',
    footerLink: '#000080',
    footerLinkHidden: '#c0c0c0',
  },
  palette: {
    yellow: '#ffff00',
    orange: '#ff8c00',
    red: '#ff0000',
    magenta: '#ff00ff',
    violet: '#800080',
    blue: '#0000ff',
    cyan: '#00ffff',
    green: '#008000',
  },
  meta: {
    fontFamily: "'Tahoma', 'MS Sans Serif', 'Arial', sans-serif",
    borderStyle: 'outset',
    cardBorderStyle: '0.2rem outset #ffffff',
    cardBoxShadow: 'none',
    codeTheme: 'vs',
    decoratorColor: '#000080',
    backgroundCss: [
      'background-image: repeating-conic-gradient(',
      '  rgba(0, 0, 0, 0.05) 0% 25%,',
      '  transparent 25% 50%,',
      '  rgba(0, 0, 0, 0.05) 50% 75%,',
      '  transparent 75% 100%',
      ');',
      'background-size: 4px 4px;',
    ].join('\n'),
    navCss: [
      'background-color: #c0c0c0;',
      'border-bottom: none;',
      'border-top: 0.2rem solid #ffffff;',
      'border-left: 0.2rem solid #ffffff;',
      'border-right: 0.2rem solid #808080;',
      'box-shadow: inset -0.1rem -0.1rem 0 #000000;',
      'color: #000000;',
    ].join('\n'),
    navLinkCss: [
      'color: #000000;',
      'padding: 0.2rem 0.8rem;',
      'border: 0.2rem solid transparent;',
      'border-bottom: none;',
      'border-radius: 0;',
      'transition: none;',
      '&:hover {',
      '  border-color: #ffffff #808080 #808080 #ffffff;',
      '  border-style: solid;',
      '}',
      '&:active {',
      '  border-color: #808080 #ffffff #ffffff #808080;',
      '}',
    ].join('\n'),
    cardCss: [
      'border: none;',
      'border-top: 0.2rem solid #ffffff;',
      'border-left: 0.2rem solid #ffffff;',
      'border-right: 0.2rem solid #000000;',
      'border-bottom: 0.2rem solid #000000;',
      'box-shadow: inset -0.1rem -0.1rem 0 #808080, inset 0.1rem 0.1rem 0 #dfdfdf;',
      'border-radius: 0;',
      'padding-top: 3.6rem;',
      'position: relative;',
      'transition: none;',
      '&::before {',
      "  content: '';",
      '  position: absolute;',
      '  top: 0;',
      '  left: 0;',
      '  right: 0;',
      '  height: 2rem;',
      '  background: linear-gradient(to right, #000080, #1084d0);',
      '  border-bottom: 0.1rem solid #808080;',
      '}',
    ].join('\n'),
    cardHoverCss: [
      'transform: none;',
      'border-top: 0.2rem solid #000000;',
      'border-left: 0.2rem solid #000000;',
      'border-right: 0.2rem solid #ffffff;',
      'border-bottom: 0.2rem solid #ffffff;',
      'box-shadow: inset 0.1rem 0.1rem 0 #808080, inset -0.1rem -0.1rem 0 #dfdfdf;',
      'background-color: #c0c0c0;',
    ].join('\n'),
    decoratorCss: [
      'height: 0.2rem;',
      'background: none;',
      'border-top: 0.1rem solid #808080;',
      'border-bottom: 0.1rem solid #ffffff;',
      'width: 100%;',
    ].join('\n'),
    headingCss: ['font-weight: 700;'].join('\n'),
    footerCss: [
      'background-color: #c0c0c0;',
      'border-top: 0.2rem solid #ffffff;',
      'box-shadow: inset 0 0.1rem 0 #dfdfdf;',
    ].join('\n'),
    globalCss: [
      'body {',
      '  -webkit-font-smoothing: none;',
      '  -moz-osx-font-smoothing: unset;',
      '}',
      '::selection {',
      '  background-color: #000080;',
      '  color: #ffffff;',
      '}',
    ].join('\n'),
  },
};
